### ISSUE TITLE
Class port does not exist

### ISSUE THREAD

**Issue by dzemba1986** [kossmoss/yii2-postgresql-array-field#1]
Hi,
I use this package and return error "Class port does not exist".

use \kossmoss\PostgresqlArrayField\PostgresqlArrayFieldBehavior;

class Model extends \yii\db\ActiveRecord
{
    public function behaviors() {
        return [
            'class' => PostgresqlArrayFieldBehavior::className(),
            'arrayFieldName' => 'port',
            'onEmptySaveNull' => true
        ];
    }
}

**Comment by kossmoss** [comment]
Hello, @dzemba1986. I not sure if error you've got caused by attaching this behavior. Do you get this error without attached behavior? If so, I suspect 'port' field is improperly declared somewhere in your model.

**Comment by dzemba1986** [comment]
This is my all code:

namespace backend\models;

use backend\models\Device;
use kossmoss\PostgresqlArrayField\PostgresqlArrayFieldBehavior;
/**
- This is the model class for table "model".
  *
- The followings are the available columns in table 'model':
- @property integer $id
- @property string $name
- @property integer $port_count
- @property integer $type
- @property integer $manufacturer
- @property array $port
  
  _/
  class Model extends \yii\db\ActiveRecord
  {
  /_*
  - @return string the associated database table name
    */
    public static function tableName()
    {
    return 'model';
    }
  
  public function behaviors() {
      return [
          'class' => PostgresqlArrayFieldBehavior::className(),
          'arrayFieldName' => 'port', // model's field to attach behavior
          'onEmptySaveNull' => true // if set to false, empty array will be saved as empty PostreSQL array '{}' (default: true)
      ];
  }
  /**
  - @return array validation rules for model attributes.
    */
    public function rules()
    {
    // NOTE: you should only define rules for those attributes that
    // will receive user inputs.
    return [
        [['name', 'port_count', 'type', 'manufacturer', 'port'], 'required'],
        [['name', 'port_count', 'type', 'manufacturer', 'port'], 'safe'],
    ];
    }
  
  /**
  - @return array customized attribute labels (name=>label)
    */
    public function attributeLabels()
    {
    return array(
        'id' => 'ID',
        'name' => 'Nazwa',
    );
    }
  
  public function getMOdelDevice(){
  
  ```
  //Wiele urzadzeń danego modelu
  return $this->hasMany(Device::className(), ['model'=>'id']);
  ```
  
  }
  }

**Comment by kossmoss** [comment]
@dzemba1986, I found this was caused by mistype in usage example and thank you for reporting this issue. Proper declaration of behavior is inside behaviors array. Your model will work with this:

```
    public function behaviors()
    {
        return [
            [
                'class' => PostgresqlArrayFieldBehavior::className(),
                'arrayFieldName' => 'port', // model's field to attach behavior
                'onEmptySaveNull' => true // if set to false, empty array will be saved as empty PostreSQL array '{}' (default: true)
            ]
        ];
    }
```
